all:
	gcc -lstdc++ -Wall -g -std=c++11 find_major_target.cpp -o ../bin/find_major_target
	gcc -lstdc++ -Wall -g -std=c++11 split_fasta.cpp -o ../bin/split_fasta
	gcc -lstdc++ -Wall -g -std=c++11 split_fastq.cpp -o ../bin/split_fastq
	gcc -lstdc++ -Wall -g -std=c++11 split_scaffold.cpp -o ../bin/split_scaffold
	gcc -lstdc++ -Wall -g -std=c++11 fasta_divider.cpp -o ../bin/fasta_divider
	chmod a+x gen_read_scaf_map; cp gen_read_scaf_map ../bin/
